export const path = {
    HOME: '/*',
    HOME__PAGE: ':page',
    LOGIN: 'dang-nhap',
    REGISTER: 'dang-ky-tai-khoan',
    RECOVERY: 'quen-mat-khau',
    TRANG_CHU: 'trang-chu',
    CHO_THUE_CAN_HO: 'cho-thue-can-ho',
    CHO_THUE_MAT_BANG: 'cho-thue-mat-bang',
    CHO_THUE_PHONG_TRO: 'cho-thue-phong-tro',
    NHA_CHO_THUE: 'nha-cho-thue',
    TIM_NGUOI_O_GHEP: 'tim-nguoi-o-ghep',
    LIEN_HE: 'lien-he',
    SEARCH: 'tim-kiem',
    BLOG: 'blog',
    DETAIL_BLOG__BLOGID: "blog/chi-tiet/:blogId",
    DETAIL_POST: 'chi-tiet/*',
    DETAIL_POST__POSTID: "chi-tiet/:postId",

    SYSTEM: '/he-thong/*',
    CREATE_POST: 'dang-tin-moi',
    MANAGE_POST: 'quan-ly-tin-dang',
    CREATE_BLOG: 'tao-moi-blog',
    MANAGE_BLOG: 'quan-ly-blog',
    MANAGE_PROFILE: 'sua-thong-tin',
    CHANGE_PASSWORD: 'doi-mat-khau',
    FORGOT_PASSWORD: 'quen-mat-khau',
    RESET_PASSWORD: 'reset-password/:token',

    MANAGE_USERS: 'quan-ly-nguoi-dung',
    MANAGE_POSTS_ADMIN: 'quan-ly-tat-ca-tin-dang',

    STATISTICS_POST: 'thong-ke/tin-dang',
    STATISTICS_USER: 'thong-ke/nguoi-dung',
    DASHBOARD: 'thong-ke/tong-quan',
}