const actionsType = {
    "LOGIN_SUCCESS": "LOGIN_SUCCESS",
    "LOGIN_FAIL": "LOGIN_FAIL",
    "LOG_OUT": "LOG_OUT",
    "SET_CURRENT_CATEGORY_CODE": "SET_CURRENT_CATEGORY_CODE",
    "SET_IS_SHOW_MENU_MANAGE": "SET_IS_SHOW_MENU_MANAGE",


    "GET_POSTS": "GET_POSTS",
    "GET_NEW_POSTS": "GET_NEW_POSTS",
    "GET_POSTS_LIMIT": "GET_POSTS_LIMIT",

    "GET_CATEGORIES": "GET_CATEGORIES",
    "GET_PRICES": "GET_PRICES",
    "GET_ACREAGES": "GET_ACREAGES",
    "GET_PROVINCES": "GET_PROVINCES",
    "GET_BLOGS": "GET_BLOGS",

    "GET_CURRENT_USER": "GET_CURRENT_USER",
    "GET_POSTS_USER": "GET_POSTS_USER",
    "GET_POSTS_BY_ID": "GET_POSTS_BY_ID",
    "GET_POSTS_FAVOURITES": "GET_POSTS_FAVOURITES",
    "SET_DATA_EDIT": "SET_DATA_EDIT",
    "CLEAR_DATA_EDIT": "CLEAR_DATA_EDIT",
    "SET_FLAG": "SET_FLAG",

    "GET_USERS_ADMIN": "GET_USERS_ADMIN",
    "SET_DATA_USER_EDIT": "SET_DATA_USER_EDIT",
    "CLEAR_DATA_USER_EDIT": "CLEAR_DATA_USER_EDIT",
    "GET_POSTS_ADMIN": "GET_POSTS_ADMIN",
    "SET_DATA_BLOG_EDIT": "SET_DATA_BLOG_EDIT",
    "CLEAR_DATA_BLOG_EDIT": "CLEAR_DATA_BLOG_EDIT",


}

export default actionsType