const actionsType = {
    "LOGIN_SUCCESS": "LOGIN_SUCCESS",
    "LOGIN_FAIL": "LOGIN_FAIL",
    "LOG_OUT": "LOG_OUT",
    "SET_CURRENT_CATEGORY_CODE": "SET_CURRENT_CATEGORY_CODE",

    "GET_POSTS": "GET_POSTS",
    "GET_NEW_POSTS": "GET_NEW_POSTS",
    "GET_POSTS_LIMIT": "GET_POSTS_LIMIT",

    "GET_CATEGORIES": "GET_CATEGORIES",
    "GET_PRICES": "GET_PRICES",
    "GET_ACREAGES": "GET_ACREAGES",
    "GET_PROVINCES": "GET_PROVINCES",

    "GET_CURRENT_USER": "GET_CURRENT_USER",
}

export default actionsType